/* Generated by scripts/build.py from templates/sw.js — do not
   edit. Edit that template and rebuild. */
/* Offline cache for the site. Rendered to /sw.js by scripts/build.py, which
   fills in the asset list and a version hash of their contents.

   SAFETY -- a service worker registered at the root controls the WHOLE origin,
   including paths that must stay on the network:

     /x17/                 the campaign hub. This repo owns it now (it was the
                           beamline's live dashboard until 2026-08-10), but it
                           is deliberately not precached: it is mostly links out
                           to reports and CERN-only storage, none of which works
                           offline, so a cached shell would only promise things
                           it cannot deliver.
     /trigger_scheme.html  standalone page, hand-published.

   Therefore the fetch handler is an ALLOWLIST, exactly like PAYLOAD in
   scripts/deploy-eos.sh: it calls respondWith() only for paths that are in the
   generated precache list, and returns without touching anything else, which
   leaves the browser's normal networking in place. Never widen this to a
   catch-all. */

const VERSION = 'c4f57ea971e5';
const CACHE = 'dneff-' + VERSION;
const ASSETS = [
  "/assets/apple-touch-icon.png",
  "/assets/icon-192.png",
  "/assets/icon-512.png",
  "/assets/icon-maskable-512.png",
  "/hub/index.html",
  "/js/live-status.js",
  "/js/notes-filter.js",
  "/js/offline.js",
  "/js/shared.js",
  "/manifest.json",
  "/notes/claude-co2-pessimistic.html",
  "/notes/index.html",
  "/notes/june-cosmic-fleet-report.html",
  "/notes/mx17-active-area.html",
  "/notes/ntof-dream-clock-qa.html",
  "/notes/ntof-dream-join-mislock.html",
  "/notes/ntof-micromegas-gamma-flash.html",
  "/notes/ntof-reprocessing-request.html",
  "/notes/offline-notes.html",
  "/notes/overnight-brief-2026-08-10.html",
  "/notes/p2-wedge-simulation-campaign.html",
  "/notes/run145-target-imaging.html",
  "/notes/standalone-example.html",
  "/notes/t14-sim-vs-data-waveforms.html",
  "/notes/wft-t0-prior-and-sharing.html",
  "/notes/x17-agent-paper-draft.html",
  "/notes/x17-where-the-six-weeks-went.html",
  "/style.css"
];

const ALLOW = new Set(ASSETS);

/* '/' and '/notes/' are the same documents as their index.html. */
function key(pathname) {
  return pathname.endsWith('/') ? pathname + 'index.html' : pathname;
}

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // One 404 must not fail the whole install and leave the site with no
    // worker at all -- take what is there and move on.
    await Promise.all(ASSETS.map((a) => cache.add(a).catch(() => {})));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((n) => n.startsWith('dneff-') && n !== CACHE)
      .map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  const path = key(url.pathname);
  if (!ALLOW.has(path)) return;   // /x17/, /trigger_scheme.html, everything else

  e.respondWith(freshen(req, path));
});

/* Serve the cached copy at once -- that is what makes this work on a plane --
   and refresh it in the background so the next open is current. */
async function freshen(req, path) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(path);

  const network = fetch(req).then((res) => {
    if (res && res.ok) cache.put(path, res.clone());
    return res;
  }).catch(() => null);

  if (hit) return hit;

  const res = await network;
  if (res) return res;
  return new Response('Offline, and this page was never cached.',
    { status: 504, headers: { 'Content-Type': 'text/plain' } });
}
