#!/usr/bin/env python3
"""Render pages/ into the deployable HTML at the repo root.

    python3 scripts/build.py            # write the output files
    python3 scripts/build.py --check    # exit 1 if any output is stale

Each file under pages/ is a body fragment with a small front-matter block:

    ---
    title: Searching for X17 at n_TOF — Dylan Neff
    description: One sentence for search results and link previews.
    skip: body
    og_type: article
    scripts: js/shared.js
    ---
    <p class="crumb">...</p>

It is combined with templates/base.html, which owns the shared chrome: the
<head>, the topbar and nav, and the footer. Change the nav once, there.

Output path mirrors the source path, so pages/projects/x17.html becomes
projects/x17.html. {{root}} in the template resolves to the relative path back
to the site root ("" at the top level, "../" one level down), which is what
makes the same nav markup work at both depths.

The generated files are committed, because they are what gets rsynced to EOS
and what a reader of this repository actually sees served. They carry a
do-not-edit banner; edit the fragment in pages/ instead.
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGES = ROOT / "pages"
TEMPLATE = ROOT / "templates" / "base.html"
SITE = "https://dylan-neff.web.cern.ch"

BANNER = ("<!-- Generated by scripts/build.py from {src} — do not edit.\n"
          "     Edit that fragment or templates/base.html and rebuild. -->\n")

DEFAULTS = {"og_type": "website", "skip": "body", "scripts": ""}


def parse_fragment(path):
    """Split a page fragment into (front matter dict, body html)."""
    text = path.read_text()
    if not text.startswith("---\n"):
        sys.exit(f"{path}: missing front-matter block")
    _, fm, body = text.split("---\n", 2)
    meta = dict(DEFAULTS)
    for line in fm.strip().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    meta.setdefault("og_description", meta.get("description", ""))
    for required in ("title", "description"):
        if required not in meta:
            sys.exit(f"{path}: front matter is missing '{required}'")
    return meta, body.strip("\n")


def script_tags(spec, root):
    """'js/a.js js/b.js' -> script tags. Inline blocks live in the fragment."""
    return "\n".join(f'<script src="{root}{s}"></script>'
                     for s in spec.split() if s)


def render(src):
    meta, body = parse_fragment(src)
    rel = src.relative_to(PAGES)
    depth = len(rel.parts) - 1
    root = "../" * depth

    canonical = f"{SITE}/" if rel.as_posix() == "index.html" \
        else f"{SITE}/{rel.as_posix()}"

    fields = {
        "root": root,
        # href="" is not a link home; the top level needs an explicit "./".
        "home": root or "./",
        "site": SITE,
        "canonical": canonical,
        "body": body,
        "scripts": script_tags(meta["scripts"], root),
        **{k: v for k, v in meta.items() if k != "scripts"},
    }

    out = TEMPLATE.read_text()
    # Plain substitution rather than str.format: the template contains literal
    # braces (the theme-boot script) that format() would choke on.
    for key, value in fields.items():
        out = out.replace("{{%s}}" % key, value)

    missing = set(re.findall(r"\{\{(\w+)\}\}", out))
    if missing:
        sys.exit(f"{src}: template placeholders never filled: {sorted(missing)}")

    return rel, BANNER.format(src=f"pages/{rel.as_posix()}") + out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify outputs match sources; write nothing")
    args = ap.parse_args()

    if not PAGES.is_dir():
        sys.exit("no pages/ directory")

    stale, written = [], []
    for src in sorted(PAGES.rglob("*.html")):
        rel, html = render(src)
        dest = ROOT / rel
        current = dest.read_text() if dest.exists() else None
        if current == html:
            continue
        if args.check:
            stale.append(rel.as_posix())
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(html)
            written.append(rel.as_posix())

    if args.check:
        if stale:
            print("stale output (run scripts/build.py):")
            for s in stale:
                print("  " + s)
            return 1
        print("all pages up to date")
        return 0

    print(f"{len(written)} page(s) rebuilt" if written else "nothing to do")
    for w in written:
        print("  " + w)
    return 0


if __name__ == "__main__":
    sys.exit(main())
