#!/usr/bin/env python3
"""Render pages/ into the deployable HTML at the repo root.

    python3 scripts/build.py            # write the output files
    python3 scripts/build.py --check    # exit 1 if any output is stale

It also generates notes/index.html (the note listing) and sw.js (the offline
cache, from templates/sw.js with the asset list filled in). See "Notes" and
"Offline" below.

Each file under pages/ is a body fragment with a small front-matter block:

    ---
    title: Searching for X17 at n_TOF — Dylan Neff
    description: One sentence for search results and link previews.
    skip: body
    og_type: article
    scripts: js/shared.js
    ---
    <p class="crumb">...</p>

It is combined with templates/base.html, which owns the shared chrome: the
<head>, the topbar and nav, and the footer. Change the nav once, there.

Output path mirrors the source path, so pages/projects/x17.html becomes
projects/x17.html. {{root}} in the template resolves to the relative path back
to the site root ("" at the top level, "../" one level down), which is what
makes the same nav markup work at both depths.

The generated files are committed, because they are what gets rsynced to EOS
and what a reader of this repository actually sees served. They carry a
do-not-edit banner; edit the fragment in pages/ instead.

Notes
-----
pages/notes/ holds notes, and accepts two shapes:

  * a fragment, exactly as above, which gets the site chrome; or
  * a complete standalone document (starts with <!doctype or <html), which is
    copied through untouched apart from an injected noindex tag, the manifest
    link and the service-worker registration.

The second is the point: a self-contained HTML file with its own styling can be
dropped in and deployed with no reformatting. Give either one a `date:` so the
listing can sort it. For a standalone document that metadata goes in an
optional comment block before the doctype:

    <!--note
    date: 2026-08-07
    title: Short title for the listing
    summary: One line for the listing.
    -->
    <!doctype html>

Falling back, a standalone note's title comes from <title> and its summary from
<meta name="description">. A note with no date sorts last; nothing is invented
for it, because a guessed date (from the mtime, say) would differ between
clones and make --check fail on a fresh checkout.

Notes are unlisted: every one carries `noindex, nofollow`, and the listing is
not linked from the site nav. Note that this is deliberately *not* paired with
a robots.txt Disallow -- blocking the crawl would stop a crawler from ever
reading the noindex, which is the tag that actually keeps them out of an index.

Offline
-------
sw.js is rendered from templates/sw.js with the precache list and a hash of
those files' contents as the cache version, so deploying a new note invalidates
the old cache on its own. Adding a file to the site means adding it to PAYLOAD
in scripts/deploy-eos.sh, and PRECACHE below if it should be readable offline.
"""

import argparse
import hashlib
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGES = ROOT / "pages"
TEMPLATE = ROOT / "templates" / "base.html"
SW_TEMPLATE = ROOT / "templates" / "sw.js"
SITE = "https://dylan-neff.web.cern.ch"

BANNER = ("<!-- Generated by scripts/build.py from {src} — do not edit.\n"
          "     Edit that fragment or templates/base.html and rebuild. -->\n")

JS_BANNER = ("/* Generated by scripts/build.py from templates/sw.js — do not\n"
             "   edit. Edit that template and rebuild. */\n")

DEFAULTS = {"og_type": "website", "skip": "body", "scripts": "",
            "robots": "", "notes_nav": "", "date": "", "summary": ""}

NOINDEX = '<meta name="robots" content="noindex, nofollow">\n'

# Files served from the cache when the network is gone: the notes, and only
# what a note needs to render. Directories are expanded; order does not matter.
#
# Scoped to the notes deliberately. The rest of the site is a live CV -- the
# home page carries the DAQ status pill and fetches publications.json, and
# neither wants to come out of a cache -- so it stays online-only. The cost is
# that the topbar nav dead-ends when you are offline, which the banner from
# js/offline.js explains.
#
# Everything NOT in here (notably /x17/, the live DAQ dashboard this repo does
# not own) is left strictly alone -- see the safety note in templates/sw.js.
PRECACHE = [
    "notes",                    # the notes themselves, and their listing
    "hub",                      # the private front door
    "style.css",                # fragment notes; standalone ones are self-contained
    "js/shared.js",             # theme toggle
    "js/offline.js",            # the "you are offline" banner
    "js/notes-filter.js",       # the listing's filter box
    "js/live-status.js",        # the hub's run pill: degrades to "status offline"
    "manifest.json",
    "assets/icon-192.png", "assets/icon-512.png",
    "assets/icon-maskable-512.png", "assets/apple-touch-icon.png",
]


def parse_meta_lines(text, into):
    """'key: value' lines into a dict. Blank lines and #comments ignored."""
    for line in text.strip().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, _, value = line.partition(":")
        into[key.strip()] = value.strip()
    return into


def parse_fragment(path):
    """Split a page fragment into (front matter dict, body html)."""
    text = path.read_text()
    if not text.startswith("---\n"):
        sys.exit(f"{path}: missing front-matter block")
    _, fm, body = text.split("---\n", 2)
    meta = parse_meta_lines(fm, dict(DEFAULTS))
    meta.setdefault("og_description", meta.get("description", ""))
    for required in ("title", "description"):
        if required not in meta:
            sys.exit(f"{path}: front matter is missing '{required}'")
    return meta, body.strip("\n")


def script_tags(spec, root):
    """'js/a.js js/b.js' -> script tags. Inline blocks live in the fragment."""
    return "\n".join(f'<script src="{root}{s}"></script>'
                     for s in spec.split() if s)


def render(rel, meta, body):
    """Combine front matter and body with the shared chrome. `rel` is the
    output path relative to the site root, which fixes {{root}}."""
    depth = len(rel.parts) - 1
    root = "../" * depth

    canonical = f"{SITE}/" if rel.as_posix() == "index.html" \
        else f"{SITE}/{rel.as_posix()}"

    if rel.parts[0] in ("notes", "hub"):
        # Unlisted: keep it out of search results, and out of the public nav --
        # but once you are inside, link across the private pages.
        meta["robots"] = NOINDEX
        meta["notes_nav"] = (f'<a href="{root}hub/">Hub</a>\n'
                             f'      <a href="{root}notes/">Notes</a>')

    fields = {
        "root": root,
        # href="" is not a link home; the top level needs an explicit "./".
        "home": root or "./",
        "site": SITE,
        "canonical": canonical,
        "body": body,
        "scripts": script_tags(meta["scripts"], root),
        **{k: v for k, v in meta.items() if k != "scripts"},
    }

    out = TEMPLATE.read_text()
    # Plain substitution rather than str.format: the template contains literal
    # braces (the theme-boot script) that format() would choke on.
    for key, value in fields.items():
        out = out.replace("{{%s}}" % key, value)

    missing = set(re.findall(r"\{\{(\w+)\}\}", out))
    if missing:
        sys.exit(f"{rel}: template placeholders never filled: {sorted(missing)}")

    return out


def render_page(src):
    """A fragment under pages/ -> (front matter, html)."""
    rel = src.relative_to(PAGES)
    meta, body = parse_fragment(src)
    banner = BANNER.format(src=f"pages/{rel.as_posix()}")
    return meta, banner + render(rel, meta, body)


# ---------------------------------------------------------------- notes ----

NOTE_META = re.compile(r"\A\s*<!--note\b(.*?)-->", re.S)
TITLE_TAG = re.compile(r"<title[^>]*>(.*?)</title>", re.S | re.I)
DESC_TAG = re.compile(
    r"""<meta\s+name=["']description["']\s+content=["'](.*?)["']""", re.I)


def is_standalone(text):
    """A complete document, rather than a fragment with front matter."""
    return re.match(r"\A\s*(<!--note\b.*?-->\s*)?<(!doctype|html)\b",
                    text, re.S | re.I) is not None


def strip_suffix(title):
    """Listing titles read better without the site's ' — Dylan Neff' tail."""
    return re.split(r"\s+[—–|]\s+Dylan Neff\s*\Z", title.strip())[0]


UNFILED = "Unfiled"


def parse_tags(spec):
    """'detector r&d, analysis' -> ['Detector r&d', 'Analysis'].

    Comma-separated, because topics are phrases: "detector R&D" is one tag.
    """
    tags = [t.strip() for t in spec.split(",")]
    return [t[0].upper() + t[1:] for t in tags if t]


def note_entry(rel, meta):
    """The listing row for one note."""
    tags = parse_tags(meta.get("tags", ""))
    return {
        "href": rel.name,
        "title": strip_suffix(meta.get("short_title") or meta["title"]),
        "summary": meta.get("summary") or meta.get("description", ""),
        "date": meta.get("date", ""),
        "tags": tags,
        # The first tag is the note's home on the listing; the rest only widen
        # what the filter box matches. One note, one section -- a note that
        # appeared under three headings would make the counts lie.
        "section": tags[0] if tags else UNFILED,
    }


def render_standalone(rel, text):
    """Copy a self-contained note through, injecting only what it needs to be
    unlisted and available offline. Its own markup and styling are untouched."""
    m = NOTE_META.match(text)
    meta = parse_meta_lines(m.group(1), {}) if m else {}
    if m:
        text = text[m.end():].lstrip("\n")

    if "title" not in meta:
        t = TITLE_TAG.search(text)
        meta["title"] = html.unescape(t.group(1).strip()) if t else rel.stem
    if "summary" not in meta:
        d = DESC_TAG.search(text)
        meta["summary"] = html.unescape(d.group(1).strip()) if d else ""

    root = "../" * (len(rel.parts) - 1)
    inject = (NOINDEX
              + f'<link rel="manifest" href="{root}manifest.json">\n'
              + f'<link rel="apple-touch-icon" href="{root}assets/apple-touch-icon.png">\n'
              + "<script>if('serviceWorker' in navigator)addEventListener("
              + f"'load',()=>navigator.serviceWorker.register('{root}sw.js')"
              + ".catch(()=>{}));</script>\n")

    if re.search(r"</head\s*>", text, re.I):
        text = re.sub(r"</head\s*>", inject + "</head>", text,
                      count=1, flags=re.I)
    else:
        sys.exit(f"pages/{rel.as_posix()}: standalone note has no </head>")

    banner = BANNER.format(src=f"pages/{rel.as_posix()}")
    return meta, banner + text


def sort_notes(entries):
    """Newest first; undated notes last rather than given an invented date.

    Two passes because sort is stable: the title ordering survives as the
    tie-break between notes sharing a date.
    """
    entries.sort(key=lambda e: e["title"])
    entries.sort(key=lambda e: (e["date"] != "", e["date"]), reverse=True)
    return entries


def note_row(e, prefix=""):
    """One <li> in a listing. `prefix` prepends a path for pages above notes/."""
    date = (f'<span class="note-date">{html.escape(e["date"])}</span>'
            if e["date"] else "")
    summary = (f'\n        <p class="note-summary">{html.escape(e["summary"])}'
               f'</p>' if e["summary"] else "")
    # The tags ride along as an attribute so the filter can match them without
    # them cluttering every row; only the secondary ones are shown, since the
    # first is already the section heading above.
    haystack = " ".join([e["title"], e["summary"], *e["tags"]]).lower()
    extra = "".join(f'<span class="note-tag">{html.escape(t)}</span>'
                    for t in e["tags"][1:])
    return (
        f'      <li class="note-item" data-find="{html.escape(haystack)}">\n'
        f'        <a class="note-link" href="{prefix}{html.escape(e["href"])}">'
        f'{html.escape(e["title"])}</a>\n'
        f'        {date}{extra}{summary}\n'
        f'      </li>')


def notes_index(entries):
    """Render notes/index.html, grouped by topic, from what was built."""
    sort_notes(entries)

    # Sections in order of most recent activity, so what you are working on now
    # is at the top. Unfiled always sits last, whatever its dates.
    sections = {}
    for e in entries:
        sections.setdefault(e["section"], []).append(e)
    order = sorted(sections, key=lambda s: sections[s][0]["date"], reverse=True)
    order.sort(key=lambda s: s == UNFILED)   # stable: pushes Unfiled to the end

    blocks = []
    for name in order:
        rows = "\n".join(note_row(e) for e in sections[name])
        blocks.append(
            f'    <section class="note-group">\n'
            f'      <h2 class="note-group-head">{html.escape(name)}'
            f'<span class="note-count">{len(sections[name])}</span></h2>\n'
            f'    <ul class="note-list">\n{rows}\n    </ul>\n'
            f'    </section>')

    listing = ("\n".join(blocks) if blocks else
               '    <p class="note-summary">No notes yet.</p>')

    meta = dict(DEFAULTS, **{
        "title": "Notes — Dylan Neff",
        "description": "Research notes and write-ups.",
        "og_description": "Research notes and write-ups.",
        "scripts": "js/shared.js js/offline.js js/notes-filter.js",
    })
    body = (
        '<p class="crumb"><a href="../hub/">← Hub</a></p>\n\n'
        '  <div class="page-head">\n'
        '    <h1>Notes</h1>\n'
        '    <p class="lede">Working notes and write-ups. Unlisted and not '
        'indexed. Install this page to your home screen and they stay '
        'readable offline.</p>\n'
        '  </div>\n\n'
        '  <div class="page-body" id="body">\n' + listing + '\n'
        '  </div>')

    rel = pathlib.Path("notes/index.html")
    banner = ("<!-- Generated by scripts/build.py from the notes in "
              "pages/notes/ — do not edit. -->\n")
    return rel, banner + render(rel, meta, body)


# ------------------------------------------------------------------ hub ----

HUB_RECENT = 6


def hub_index(entries):
    """A private front door: recent notes, the live run, and the CV links.

    Generated rather than hand-written because the recent-notes block has to
    track pages/notes/ -- the same reason notes/index.html is generated.
    """
    recent = sort_notes(list(entries))[:HUB_RECENT]
    rows = "\n".join(note_row(e, prefix="../notes/") for e in recent)
    more = (f'<p class="card-more"><a href="../notes/">All '
            f'{len(entries)} notes →</a></p>' if len(entries) > HUB_RECENT
            else '<p class="card-more"><a href="../notes/">All notes →</a></p>')

    meta = dict(DEFAULTS, **{
        "title": "Hub — Dylan Neff",
        "description": "Personal entry point: recent notes, the live run, "
                       "and the rest of the site.",
        "og_description": "Personal entry point.",
        "skip": "body",
        "scripts": "js/shared.js js/live-status.js js/offline.js",
    })
    body = (
        '<div class="page-head">\n'
        '    <h1>Hub</h1>\n'
        '    <p class="lede">Everything of mine, in one place. Unlisted.</p>\n'
        '  </div>\n\n'
        '  <div class="page-body" id="body">\n'
        '    <section class="note-group">\n'
        '      <h2 class="note-group-head">Recent notes</h2>\n'
        f'    <ul class="note-list">\n{rows}\n    </ul>\n'
        f'    {more}\n'
        '    </section>\n\n'
        '    <section class="note-group">\n'
        '      <h2 class="note-group-head">Live</h2>\n'
        '      <p class="pill" id="live-pill"><span class="dot"></span>'
        '<span id="live-pill-text">status offline</span></p>\n'
        '      <ul class="hub-links">\n'
        '        <li><a href="../x17/">x17 DAQ dashboard →</a></li>\n'
        '        <li><a href="../trigger_scheme.html">Trigger scheme →</a></li>\n'
        '      </ul>\n'
        '    </section>\n\n'
        '    <section class="note-group">\n'
        '      <h2 class="note-group-head">Elsewhere</h2>\n'
        '      <ul class="hub-links">\n'
        '        <li><a href="../cv/Dylan_Neff_CV.pdf">CV (PDF) →</a></li>\n'
        '        <li><a href="../">Public site →</a></li>\n'
        '        <li><a href="../projects/x17.html">X17 at n_TOF →</a></li>\n'
        '        <li><a href="../projects/micromegas.html">Micromegas R&amp;D →</a></li>\n'
        '        <li><a href="../projects/sphenix.html">sPHENIX luminosity →</a></li>\n'
        '        <li><a href="../projects/qgp.html">QGP &amp; the BES →</a></li>\n'
        '        <li><a href="https://inspirehep.net/authors/1763981">INSPIRE →</a></li>\n'
        '      </ul>\n'
        '    </section>\n'
        '  </div>')

    rel = pathlib.Path("hub/index.html")
    banner = ("<!-- Generated by scripts/build.py — do not edit. -->\n")
    return rel, banner + render(rel, meta, body)


# -------------------------------------------------------------- offline ----

def precache_list():
    """Absolute paths for every file the offline cache should hold."""
    paths = []
    for item in PRECACHE:
        p = ROOT / item
        if p.is_dir():
            paths += [f.relative_to(ROOT).as_posix()
                      for f in sorted(p.rglob("*")) if f.is_file()]
        elif p.is_file():
            paths.append(item)
    # Only the index.html spellings go in. '/' and '/notes/' are how these are
    # actually requested, but the worker's key() folds a trailing slash onto
    # index.html before it consults the list, so listing them again would just
    # download the same document twice at install.
    return sorted({"/" + p for p in paths})


def prune_notes(keep, check):
    """Delete published notes whose source under pages/notes/ is gone.

    Without this, deleting a note leaves it served -- and, worse, still in the
    precache list, so it would keep reappearing offline. Only files carrying
    the generated banner are ever removed: anything else in notes/ was put
    there by hand and is not this script's to delete.
    """
    out = ROOT / "notes"
    if not out.is_dir():
        return []

    orphans = []
    for f in sorted(out.glob("*.html")):
        if f.name in keep:
            continue
        if not f.read_text().startswith("<!-- Generated by scripts/build.py"):
            print(f"  warning: notes/{f.name} is not generated — leaving it")
            continue
        orphans.append(f"notes/{f.name}")
        if not check:
            f.unlink()
    return orphans


def render_sw(urls):
    """templates/sw.js + the asset list + a content hash for the cache name."""
    h = hashlib.sha256()
    for u in urls:
        f = ROOT / u.lstrip("/")
        h.update(u.encode())
        if f.is_file():
            h.update(f.read_bytes())
    version = h.hexdigest()[:12]

    assets = "[\n" + ",\n".join(f"  {json.dumps(u)}" for u in urls) + "\n]"
    out = SW_TEMPLATE.read_text()
    out = out.replace("{{version}}", version).replace("{{assets}}", assets)
    return pathlib.Path("sw.js"), JS_BANNER + out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify outputs match sources; write nothing")
    args = ap.parse_args()

    if not PAGES.is_dir():
        sys.exit("no pages/ directory")

    stale, written = [], []

    def emit(rel, text):
        dest = ROOT / rel
        current = dest.read_text() if dest.exists() else None
        if current == text:
            return
        if args.check:
            stale.append(rel.as_posix())
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(text)
            written.append(rel.as_posix())

    notes, note_files = [], {"index.html"}
    for src in sorted(PAGES.rglob("*.html")):
        rel = src.relative_to(PAGES)
        note = rel.parts[0] == "notes"

        if note and rel.name == "index.html":
            sys.exit(f"{src}: notes/index.html is generated from the other "
                     "notes; remove this file")

        text = src.read_text()
        if is_standalone(text):
            if not note:
                sys.exit(f"{src}: standalone documents are only supported "
                         "under pages/notes/")
            meta, out = render_standalone(rel, text)
        else:
            meta, out = render_page(src)

        if note:
            notes.append(note_entry(rel, meta))
            note_files.add(rel.name)
        emit(rel, out)

    emit(*notes_index(notes))
    emit(*hub_index(notes))
    orphans = prune_notes(note_files, args.check)
    # Last: the cache version is a hash of the files above, which have to be
    # on disk in their final form before it can be computed.
    emit(*render_sw(precache_list()))

    if args.check:
        if stale or orphans:
            print("stale output (run scripts/build.py):")
            for s in stale:
                print("  " + s)
            for o in orphans:
                print(f"  {o} — published but its source is gone")
            return 1
        print("all pages up to date")
        return 0

    print(f"{len(written)} page(s) rebuilt" if written else "nothing to do")
    for w in written:
        print("  " + w)
    for o in orphans:
        print(f"  removed {o} (source deleted)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
